export ASDF_DATA_DIR="/home/john/.asdf-data"
export GOPATH="$HOME/go"
export NVM_DIR="$HOME/.nvm"
export FZF_DEFAULT_COMMAND='rg'
export DOTBARE_DIR="$HOME/.cfg"
export DOTBARE_TREE="$HOME"
export PATH="/opt/asdf-vm/bin:$HOME/.config/emacs/bin/:$GOPATH/bin:$ASDF_DATA_DIR/shims:$HOME/.local/bin:$PATH"
export EDITOR="nvim"
export BW_SESSION="mLQQ8CYRVVrdZM2R8OVz4dLL4C1YW1yEx4ZMaMuWL059J8nIKiiwffbbs+4hL624Qf3wikL6MN6ZbLwE/XcQzA=="
