export ASDF_DATA_DIR="/Users/matheus.ashton/.asdf-data"
export GO_PATH="$HOME/go"
export NVM_DIR="$HOME/.nvm"
export GPG_TTY=$(tty)
export JAVA_HOME=`/usr/libexec/java_home -v 11`
export HOMEBREW_BUNDLE_FILE=$HOME/.config/Brewfile
export FZF_DEFAULT_COMMAND='rg'
export ZPLUG_HOME=/usr/local/opt/zplug
export DOTBARE_DIR="$HOME/.cfg"
export DOTBARE_TREE="$HOME"
export PATH="$PATH:~/.emacs.d/bin/"
