require 'mappings/plugins/nvim-tree'
require 'mappings/plugins/vim-test'
require 'mappings/plugins/barbar'
require 'mappings/plugins/telescope'
require 'mappings/plugins/compe'
require 'mappings/plugins/lsp-saga'
