return {
  { "<bs><bs>", desc = "Clear search highlights" },
  { "<tab>", "%", desc = "go to matching part", mode = { "n" } },
  { "<leader>b", group = "buffer", icon = { "󰪷" } },
  { "<leader>bn", "<CMD>bn<CR>", desc = "Go to next buffer" },
  { "<leader>bp", "<CMD>bp<CR>", desc = "Go to previous buffer" },
  { "<leader>bl", "<CMD>b#<CR>", desc = "Go to last buffer" },
  { "<leader>c", group = "code", icon = { "󰘦" } },
  { "<leader>cf", "<CMD>lua vim.lsp.buf.format()<CR>", desc = "format buffer using LSP" },
  { "<leader>d", group = "debug", icon = { "" } },
  { "<leader>f", group = "file", icon = { "󱧶" } },
  { "<leader>g", group = "git", icon = { "󰊢" } },
  { "<leader>p", group = "projects" },
  { "<leader>s", group = "search", icon = { "󰥨" } },
  { "<leader>w", group = "window", proxy = "<C-W>", icon = { "" } },
  { "<leader>x", group = "diagnostics", icon = { "" } },
  { "[", group = "previous", icon = { "" } },
  { "[e", "<CMD>lua vim.diagnostic.goto_prev()<CR>", desc = "Go to previous diagnostic" },
  { "]", group = "next", icon = { "" } },
  { "]e", "<CMD>lua vim.diagnostic.goto_next()<CR>", desc = "Go to next diagnostic" },
  { "g", group = "goto", icon = { "" } },
  { "z", group = "fold", icon = { "" } },
}
