name: update-os-branches
on: [push]
jobs:
  update-osx-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git rebase --onto osx main
      - run: git push
  update-arch-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git rebase --onto arch main
      - run: git push
